apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: "10.100.208.180"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  #<THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: <OUTPUT OF `echo -n 'the password' | base64`>
  db_password: bXlwYXNzd29yZA==